apiVersion: v1
kind: Pod
metadata:
  name: cleanup-pod
  namespace: wiki
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: postgres-data
          mountPath: /data
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: postgres-data-postgres-1
  restartPolicy: Never
