apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/shlomo-b/Wiki-project.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/bitnami/charts.git
      path: bitnami/metrics-server
      targetRevision: metrics-server/7.4.5
      helm:
        valueFiles:
          - "$values/app-of-apps/metrics-server/values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-server
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
