apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-credentials
  namespace: monitoring
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: aws-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: keys