apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/shlomo-b/Wiki-project.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/bitnami/charts/tree/main/bitnami/external-dns
      chart:  external-dns
      targetRevision: 8.8.3
      helm:
        valueFiles:
          - $values/app-of-apps/external-dns/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
