apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-credentials
  namespace: monitoring
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: aws-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: keys

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wiki-credentials
  namespace: wiki
spec:
  refreshInterval: 5m # how often the secret should be updated
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: aws-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: wiki-credentials