apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: externalsecrets-applications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shlomo-b/Wiki-project.git
    path: apps/manage-secrets-apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    # syncOptions:
    #   - CreateNamespace=true
    automated:
      selfHeal: true 
      prune: true