apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/shlomo-b/Wiki-project.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.17.0
      helm:
        valueFiles:
          - $values/app-of-apps/external-secrets/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
