enabled: true

serviceAccount:
  create: true  

server:
  global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s

  service:
    enabled: true
    type: ClusterIP
    targetPort: 3000

  persistentVolume:
    enabled: false


serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'node-exporter-nodes'
        metrics_path: /metrics
        static_configs:
          - targets:
              - "master:9100"
      - job_name: 'kubernetes-pods'
        honor_labels: true
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true        

alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: false  

prometheus-node-exporter:
  enabled: true
  service:
    type: ClusterIP
    port: 9100
    targetPort: 9100
    PortName: metrics
    name: node-exporter
