apiVersion: v1
kind: ConfigMap
metadata:
    namespace: wiki
    name: wiki-config-wiki-app
data:
   DB_TYPE: postgres
   DB_HOST: postgres
   DB_PORT: "5432"
   DB_NAME: wiki

---
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: wiki
    name: db-postgres-config
data:
   POSTGRES_DB: wiki