apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-wiki
  namespace: wiki
spec:
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
        - name: wiki
          image: ghcr.io/requarks/wiki:2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: DB_USER
                  
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: DB_PASS

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: wiki-config-wiki-app
                  key: DB_HOST 

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: wiki-config-wiki-app
                  key:  DB_NAME   

            - name: DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: wiki-config-wiki-app
                  key: DB_TYPE

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: wiki-config-wiki-app
                  key: DB_PORT
                  
---
apiVersion: v1
kind: Service
metadata:
  name: svc-wiki
  namespace: wiki
spec:
  selector:
    app: wiki
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
