apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-blackjack
  namespace: blackjack
  annotations:
    # annotations for keel to update the image
    keel.sh/policy: "all"
    keel.sh/trigger: "poll"
    keel.sh/pollSchedule: "@every 3m"
spec:
  selector:
    matchLabels:
      app: blackjack
  replicas: 1
  template:
    metadata:
      labels:
        app: blackjack
    spec:
      containers:
      - name: blackjack
        image: shlomobarzili/blackjack:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

        env:
          # - name: DATABASE_HOST
          #   valueFrom:
          #     configMapKeyRef:
          #       name: variables
          #       key: DATABASE_HOST
          # - name: DATABASE_NAME
          #   valueFrom:
          #     configMapKeyRef:
          #       name: variables
          #       key: DATABASE_NAME

          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: aws-secret       # reference from ExternalSecret
                key: MONGO_INITDB_ROOT_USERNAME

          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aws-secret      # reference from ExternalSecret
                key: MONGO_INITDB_ROOT_PASSWORD      

        volumeMounts:
        - name: blackjack-storage
          mountPath: /storage-data
      volumes:
      - name: blackjack-storage
        persistentVolumeClaim:
          claimName: blackjack-pvc